<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "Topic".
 *
 * @property integer $top_id
 * @property string $top_name
 * @property integer $top_tra_id
 *
 * @property \common\models\Travel $topTra
 * @property \common\models\TopicProposal[] $topicProposals
 * @property \common\models\WallComment[] $wallComments
 * @property string $aliasModel
 */
abstract class Topic extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Topic';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'Topics');
        }else{
            return Yii::t('app', 'Topic');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['top_name', 'top_tra_id'], 'required'],
            [['top_tra_id'], 'integer'],
            [['top_name'], 'string', 'max' => 1000],
            [['top_tra_id'], 'exist', 'skipOnError' => true, 'targetClass' => Travel::className(), 'targetAttribute' => ['top_tra_id' => 'tra_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'top_id' => 'Top ID',
            'top_name' => 'Top Name',
            'top_tra_id' => 'Top Tra ID',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'top_id' => 'Top Id',
            'top_name' => 'Top Name',
            'top_tra_id' => 'Top Tra Id',
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTopTra()
    {
        return $this->hasOne(\common\models\Travel::className(), ['tra_id' => 'top_tra_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTopicProposals()
    {
        return $this->hasMany(\common\models\TopicProposal::className(), ['pro_top_id' => 'top_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWallComments()
    {
        return $this->hasMany(\common\models\WallComment::className(), ['com_top_id' => 'top_id']);
    }




}
