<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "Travel".
 *
 * @property integer $tra_id
 * @property string $tra_origin
 * @property string $tra_destination
 * @property integer $tra_num_days
 * @property double $tra_budget_min
 * @property double $tra_budget_max
 * @property string $tra_date
 * @property double $tra_lat
 * @property double $tra_long
 * @property string $tra_planning_limit
 * @property integer $tra_persons_min
 * @property integer $tra_persons_max
 * @property string $tra_description
 * @property integer $tra_usr_id
 *
 * @property \common\models\Route[] $routes
 * @property \common\models\Topic[] $topics
 * @property \common\models\User $traUsr
 * @property \common\models\UserTravel[] $userTravels
 * @property string $aliasModel
 */
abstract class Travel extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Travel';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'Travels');
        }else{
            return Yii::t('app', 'Travel');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tra_origin', 'tra_destination', 'tra_num_days', 'tra_date', 'tra_lat', 'tra_long', 'tra_planning_limit', 'tra_description', 'tra_usr_id'], 'required'],
            [['tra_num_days', 'tra_persons_min', 'tra_persons_max', 'tra_usr_id'], 'integer'],
            [['tra_budget_min', 'tra_budget_max', 'tra_lat', 'tra_long'], 'number'],
            [['tra_date', 'tra_planning_limit'], 'safe'],
            [['tra_origin', 'tra_destination'], 'string', 'max' => 255],
            [['tra_description'], 'string', 'max' => 4000],
            [['tra_usr_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['tra_usr_id' => 'usr_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'tra_id' => 'Tra ID',
            'tra_origin' => 'Tra Origin',
            'tra_destination' => 'Tra Destination',
            'tra_num_days' => 'Tra Num Days',
            'tra_budget_min' => 'Tra Budget Min',
            'tra_budget_max' => 'Tra Budget Max',
            'tra_date' => 'Tra Date',
            'tra_lat' => 'Tra Lat',
            'tra_long' => 'Tra Long',
            'tra_planning_limit' => 'Tra Planning Limit',
            'tra_persons_min' => 'Tra Persons Min',
            'tra_persons_max' => 'Tra Persons Max',
            'tra_description' => 'Tra Description',
            'tra_usr_id' => 'Tra Usr ID',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'tra_id' => 'Tra Id',
            'tra_origin' => 'Tra Origin',
            'tra_destination' => 'Tra Destination',
            'tra_num_days' => 'Tra Num Days',
            'tra_budget_min' => 'Tra Budget Min',
            'tra_budget_max' => 'Tra Budget Max',
            'tra_date' => 'Tra Date',
            'tra_lat' => 'Tra Lat',
            'tra_long' => 'Tra Long',
            'tra_planning_limit' => 'Tra Planning Limit',
            'tra_persons_min' => 'Tra Persons Min',
            'tra_persons_max' => 'Tra Persons Max',
            'tra_description' => 'Tra Description',
            'tra_usr_id' => 'Tra Usr Id',
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoutes()
    {
        return $this->hasMany(\common\models\Route::className(), ['rut_tra_id' => 'tra_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTopics()
    {
        return $this->hasMany(\common\models\Topic::className(), ['top_tra_id' => 'tra_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTraUsr()
    {
        return $this->hasOne(\common\models\User::className(), ['usr_id' => 'tra_usr_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserTravels()
    {
        return $this->hasMany(\common\models\UserTravel::className(), ['ust_tra_id' => 'tra_id']);
    }




}
