<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "User".
 *
 * @property integer $usr_id
 * @property string $usr_name
 * @property string $usr_surname
 * @property string $usr_nickname
 * @property string $usr_mail
 * @property string $usr_password
 * @property string $usr_birthday
 * @property boolean $usr_gender
 * @property string $usr_register_date
 * @property string $usr_avatar_url
 *
 * @property \common\models\TopicProposal[] $topicProposals
 * @property \common\models\Travel[] $travels
 * @property \common\models\UserTravel[] $userTravels
 * @property \common\models\Vote[] $votes
 * @property \common\models\WallComment[] $wallComments
 * @property string $aliasModel
 */
abstract class User extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'User';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'Users');
        }else{
            return Yii::t('app', 'User');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['usr_name', 'usr_surname', 'usr_nickname', 'usr_mail', 'usr_password', 'usr_birthday'], 'required'],
            [['usr_birthday', 'usr_register_date'], 'safe'],
            [['usr_gender'], 'boolean'],
            [['usr_name', 'usr_surname', 'usr_nickname', 'usr_mail', 'usr_password'], 'string', 'max' => 255],
            [['usr_avatar_url'], 'string', 'max' => 1000]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'usr_id' => 'Usr ID',
            'usr_name' => 'Usr Name',
            'usr_surname' => 'Usr Surname',
            'usr_nickname' => 'Usr Nickname',
            'usr_mail' => 'Usr Mail',
            'usr_password' => 'Usr Password',
            'usr_birthday' => 'Usr Birthday',
            'usr_gender' => 'Usr Gender',
            'usr_register_date' => 'Usr Register Date',
            'usr_avatar_url' => 'Usr Avatar Url',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'usr_id' => 'Usr Id',
            'usr_name' => 'Usr Name',
            'usr_surname' => 'Usr Surname',
            'usr_nickname' => 'Usr Nickname',
            'usr_mail' => 'Usr Mail',
            'usr_password' => 'Usr Password',
            'usr_birthday' => 'Usr Birthday',
            'usr_gender' => 'Usr Gender',
            'usr_register_date' => 'Usr Register Date',
            'usr_avatar_url' => 'Usr Avatar Url',
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTopicProposals()
    {
        return $this->hasMany(\common\models\TopicProposal::className(), ['pro_usr_id' => 'usr_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTravels()
    {
        return $this->hasMany(\common\models\Travel::className(), ['tra_usr_id' => 'usr_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserTravels()
    {
        return $this->hasMany(\common\models\UserTravel::className(), ['ust_usr_id' => 'usr_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVotes()
    {
        return $this->hasMany(\common\models\Vote::className(), ['vot_usr_id' => 'usr_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWallComments()
    {
        return $this->hasMany(\common\models\WallComment::className(), ['com_usr_id' => 'usr_id']);
    }




}
